// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcGz3Uaq9BSNgCHXo7Hy7HwEF-Tq-C1pk',
    appId: '1:645222474116:web:16e350d764758a745c7dd1',
    messagingSenderId: '645222474116',
    projectId: 'khata-app-c91b1',
    authDomain: 'khata-app-c91b1.firebaseapp.com',
    storageBucket: 'khata-app-c91b1.appspot.com',
    measurementId: 'G-NSS94YTS2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM60h0ONH5udJRKbWkxt4AMl0Fr4lK-TY',
    appId: '1:645222474116:android:1f0e71b55378f66c5c7dd1',
    messagingSenderId: '645222474116',
    projectId: 'khata-app-c91b1',
    storageBucket: 'khata-app-c91b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPaPel1o2cczPcQGAmJjjN55OS-7XUjg8',
    appId: '1:645222474116:ios:3a4bfcf54db177f35c7dd1',
    messagingSenderId: '645222474116',
    projectId: 'khata-app-c91b1',
    storageBucket: 'khata-app-c91b1.appspot.com',
    iosBundleId: 'com.ahmad.rajpoot.flutte.khataApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPaPel1o2cczPcQGAmJjjN55OS-7XUjg8',
    appId: '1:645222474116:ios:3a4bfcf54db177f35c7dd1',
    messagingSenderId: '645222474116',
    projectId: 'khata-app-c91b1',
    storageBucket: 'khata-app-c91b1.appspot.com',
    iosBundleId: 'com.ahmad.rajpoot.flutte.khataApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcGz3Uaq9BSNgCHXo7Hy7HwEF-Tq-C1pk',
    appId: '1:645222474116:web:4054c29bb1d8a4db5c7dd1',
    messagingSenderId: '645222474116',
    projectId: 'khata-app-c91b1',
    authDomain: 'khata-app-c91b1.firebaseapp.com',
    storageBucket: 'khata-app-c91b1.appspot.com',
    measurementId: 'G-9JHR5S8RJL',
  );
}
